import { useState } from "react";
import "./App.css";

function App() {
  const [message, setMessage] = useState("");

  const [messages, setMessages] = useState([
    {
      role: "ai",
      text: "Hi! Tell me what symptoms you're experiencing, and we'll start there.",
    },
  ]);

  // Stores the current question generated by the AI
  const [currentQuestion, setCurrentQuestion] = useState(null);

  // Stores the user's current answer
  const [selectedValue, setSelectedValue] = useState(null);

  const sendAnswer = async (answer) => {
    const trimmedAnswer = String(answer).trim();

    if (!trimmedAnswer) {
      return;
    }

    // Add user's answer to the visible conversation
    setMessages((currentMessages) => [
      ...currentMessages,
      {
        role: "user",
        text: trimmedAnswer,
      },
    ]);

    // Clear the current interactive question
    setCurrentQuestion(null);
    setSelectedValue(null);

    try {
      const response = await fetch(
        `/api/chat?message=${encodeURIComponent(trimmedAnswer)}`,
        {
          method: "POST",
        }
      );

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      const data = await response.json();

      // Add the AI's question to the visible conversation
      setMessages((currentMessages) => [
        ...currentMessages,
        {
          role: "ai",
          text: data.question,
        },
      ]);

      // Save the question information so we can render
      // the appropriate UI component
      setCurrentQuestion(data);
    } catch (error) {
      console.error("Error contacting backend:", error);

      setMessages((currentMessages) => [
        ...currentMessages,
        {
          role: "ai",
          text: "Sorry, I couldn't connect to the server.",
        },
      ]);
    }
  };

  // Used when the user sends a free-text response
  const handleSubmit = async (event) => {
    event.preventDefault();

    if (!message.trim()) {
      return;
    }

    await sendAnswer(message);
    setMessage("");
  };

  // Used for single-choice questions
  const handleSingleChoice = (choice) => {
    setSelectedValue(choice);
  };

  // Used for select-all questions
  const handleSelectAll = (choice) => {
    setSelectedValue((currentValues) => {
      const values = Array.isArray(currentValues) ? currentValues : [];

      if (values.includes(choice)) {
        return values.filter((value) => value !== choice);
      }

      return [...values, choice];
    });
  };

  // Sends the selected interactive answer to the backend
  const handleContinue = async () => {
    if (currentQuestion?.input_type === "select_all") {
      if (!Array.isArray(selectedValue) || selectedValue.length === 0) {
        return;
      }

      await sendAnswer(selectedValue.join(", "));
      return;
    }

    if (selectedValue === null || selectedValue === "") {
      return;
    }

    await sendAnswer(selectedValue);
  };

  // Determines which input control should be displayed
  // based on the AI's requested input type
  const renderInput = () => {
    if (!currentQuestion) {
      return null;
    }

    /*
     * SCALE
     * Example:
     * "How severe is your pain?"
     */
    if (currentQuestion.input_type === "scale") {
      return (
        <div className="interactive-input">
          <input
            type="range"
            min="0"
            max="10"
            value={selectedValue ?? 5}
            onChange={(event) =>
              setSelectedValue(Number(event.target.value))
            }
          />

          <div className="scale-labels">
            <span>0</span>
            <strong>{selectedValue ?? 5}</strong>
            <span>10</span>
          </div>

          <button type="button" onClick={handleContinue}>
            Continue
          </button>
        </div>
      );
    }

    /*
     * SINGLE CHOICE
     * Example:
     * "Where does the pain occur?"
     */
    if (currentQuestion.input_type === "single_choice") {
      return (
        <div className="interactive-input">
          <div className="choice-list">
            {currentQuestion.options?.map((option) => (
              <label key={option} className="choice-option">
                <input
                  type="radio"
                  name="single-choice"
                  value={option}
                  checked={selectedValue === option}
                  onChange={() => handleSingleChoice(option)}
                />

                <span>{option}</span>
              </label>
            ))}
          </div>

          <button
            type="button"
            onClick={handleContinue}
            disabled={!selectedValue}
          >
            Continue
          </button>
        </div>
      );
    }

    /*
     * SELECT ALL
     * Example:
     * "Which symptoms are you experiencing?"
     */
    if (currentQuestion.input_type === "select_all") {
      const selectedOptions = Array.isArray(selectedValue)
        ? selectedValue
        : [];

      return (
        <div className="interactive-input">
          <div className="choice-list">
            {currentQuestion.options?.map((option) => (
              <label key={option} className="choice-option">
                <input
                  type="checkbox"
                  value={option}
                  checked={selectedOptions.includes(option)}
                  onChange={() => handleSelectAll(option)}
                />

                <span>{option}</span>
              </label>
            ))}
          </div>

          <button
            type="button"
            onClick={handleContinue}
            disabled={selectedOptions.length === 0}
          >
            Continue
          </button>
        </div>
      );
    }

    /*
     * TEXT
     * Used when the user needs to explain something
     * in their own words.
     */
    return (
      <form className="input-area" onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Type your answer..."
          value={message}
          onChange={(event) => setMessage(event.target.value)}
        />

        <button type="submit">Send</button>
      </form>
    );
  };

  return (
    <div className="app">
      <header className="header">
        <div>
          <h1>Doctor AI</h1>
          <p>Your health assessment assistant</p>
        </div>
      </header>

      <main className="chat-container">
        <div className="welcome-message">
          <h2>How are you feeling?</h2>

          <p>
            Describe your symptoms and I'll ask questions to better
            understand what's going on.
          </p>
        </div>

        <div className="messages">
          {messages.map((msg, index) => (
            <div
              key={index}
              className={`message ${
                msg.role === "user" ? "user-message" : "ai-message"
              }`}
            >
              <strong>
                {msg.role === "user" ? "You" : "Doctor AI"}
              </strong>

              <p>{msg.text}</p>
            </div>
          ))}
        </div>
      </main>

      {currentQuestion ? (
        <div className="question-area">
          {renderInput()}
        </div>
      ) : (
        <form className="input-area" onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Describe your symptoms..."
            value={message}
            onChange={(event) => setMessage(event.target.value)}
          />

          <button type="submit">Send</button>
        </form>
      )}
    </div>
  );
}

export default App;