import { useState } from "react";
import "./App.css";

function App() {
  const [message, setMessage] = useState("");

  const [messages, setMessages] = useState([
    {
      role: "ai",
      text: "Hi! Tell me what symptoms you're experiencing, and we'll start there.",
    },
  ]);

  // Stores the current question generated by the AI
  const [currentQuestion, setCurrentQuestion] = useState(null);

  // Stores the user's current answer
  const [selectedValue, setSelectedValue] = useState(null);

  // Stores the latest assessment data received from the AI
  const [assessment, setAssessment] = useState(null);

  // Tracks whether the AI is currently responding
  const [isLoading, setIsLoading] = useState(false);

  const sendAnswer = async (answer) => {
    const trimmedAnswer = String(answer).trim();

    if (!trimmedAnswer || isLoading) {
      return;
    }

    // Show the user's answer in the conversation
    setMessages((currentMessages) => [
      ...currentMessages,
      {
        role: "user",
        text: trimmedAnswer,
      },
    ]);

    // Clear the current interactive question
    setCurrentQuestion(null);
    setSelectedValue(null);

    // Show loading state
    setIsLoading(true);

    try {
      const response = await fetch(
        `/api/chat?message=${encodeURIComponent(trimmedAnswer)}`,
        {
          method: "POST",
        }
      );

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      const data = await response.json();

      /*
       * Update the assessment after every AI response.
       * This allows the sidebar to evolve throughout
       * the interview instead of only appearing at the end.
       */
      setAssessment((currentAssessment) => ({
        summary: data.summary ?? currentAssessment?.summary ?? null,
        possibilities:
          data.possibilities ?? currentAssessment?.possibilities ?? [],
        urgency: data.urgency ?? currentAssessment?.urgency ?? null,
        assessment_complete:
          data.assessment_complete ??
          currentAssessment?.assessment_complete ??
          false,
      }));

      /*
       * If the assessment is complete, show the completion
       * message and stop asking follow-up questions.
       */
      if (data.assessment_complete) {
        setMessages((currentMessages) => [
          ...currentMessages,
          {
            role: "ai",
            text: "I've gathered enough information to provide a preliminary assessment.",
          },
        ]);

        return;
      }

      /*
       * Otherwise, show the next question.
       */
      setMessages((currentMessages) => [
        ...currentMessages,
        {
          role: "ai",
          text: data.question,
        },
      ]);

      // Save the question so the correct input control can be rendered
      setCurrentQuestion(data);

    } catch (error) {
      console.error("Error contacting backend:", error);

      setMessages((currentMessages) => [
        ...currentMessages,
        {
          role: "ai",
          text: "Sorry, I couldn't connect to the server.",
        },
      ]);
    } finally {
      // Always stop the loading state when the request finishes
      setIsLoading(false);
    }
  };

  // Used when the user sends a free-text response
  const handleSubmit = async (event) => {
    event.preventDefault();

    if (!message.trim()) {
      return;
    }

    await sendAnswer(message);
    setMessage("");
  };

  // Used for single-choice questions
  const handleSingleChoice = (choice) => {
    setSelectedValue(choice);
  };

  // Used for select-all questions
  const handleSelectAll = (choice) => {
    setSelectedValue((currentValues) => {
      const values = Array.isArray(currentValues) ? currentValues : [];

      if (values.includes(choice)) {
        return values.filter((value) => value !== choice);
      }

      return [...values, choice];
    });
  };

  // Sends the selected interactive answer to the backend
  const handleContinue = async () => {
    if (currentQuestion?.input_type === "select_all") {
      if (!Array.isArray(selectedValue) || selectedValue.length === 0) {
        return;
      }

      await sendAnswer(selectedValue.join(", "));
      return;
    }

    if (selectedValue === null || selectedValue === "") {
      return;
    }

    await sendAnswer(selectedValue);
  };

  // Determines which input control should be displayed
  // based on the AI's requested input type
  const renderInput = () => {
    if (!currentQuestion) {
      return null;
    }

    /*
     * SCALE
     */
    if (currentQuestion.input_type === "scale") {
      return (
        <div className="interactive-input">
          <input
            type="range"
            min="0"
            max="10"
            value={selectedValue ?? 5}
            onChange={(event) =>
              setSelectedValue(Number(event.target.value))
            }
          />

          <div className="scale-labels">
            <span>0</span>
            <strong>{selectedValue ?? 5}</strong>
            <span>10</span>
          </div>

          <button type="button" onClick={handleContinue}>
            Continue
          </button>
        </div>
      );
    }

    /*
     * SINGLE CHOICE
     */
    if (currentQuestion.input_type === "single_choice") {
      return (
        <div className="interactive-input">
          <div className="choice-list">
            {currentQuestion.options?.map((option) => (
              <label key={option} className="choice-option">
                <input
                  type="radio"
                  name="single-choice"
                  value={option}
                  checked={selectedValue === option}
                  onChange={() => handleSingleChoice(option)}
                />

                <span>{option}</span>
              </label>
            ))}
          </div>

          <button
            type="button"
            onClick={handleContinue}
            disabled={!selectedValue || isLoading}
          >
            Continue
          </button>
        </div>
      );
    }

    /*
     * SELECT ALL
     */
    if (currentQuestion.input_type === "select_all") {
      const selectedOptions = Array.isArray(selectedValue)
        ? selectedValue
        : [];

      return (
        <div className="interactive-input">
          <div className="choice-list">
            {currentQuestion.options?.map((option) => {
              const isSelected = selectedOptions.includes(option);

              return (
                <label key={option} className="choice-option">
                  <input
                    type="checkbox"
                    value={option}
                    checked={isSelected}
                    onChange={() => handleSelectAll(option)}
                  />

                  <span>{option}</span>
                </label>
              );
            })}
          </div>

          <button
            type="button"
            onClick={handleContinue}
            disabled={selectedOptions.length === 0 || isLoading}
          >
            Continue
          </button>
        </div>
      );
    }

    /*
     * TEXT
     */
    return (
      <form className="input-area" onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Type your answer..."
          value={message}
          disabled={isLoading}
          onChange={(event) => setMessage(event.target.value)}
        />

        <button type="submit" disabled={isLoading}>
          {isLoading ? "Thinking..." : "Send"}
        </button>
      </form>
    );
  };

  return (
    <div className="app">

      <header className="header">
        <div>
          <h1>Doctor AI</h1>
          <p>Your health assessment assistant</p>
        </div>
      </header>

      <div className="app-layout">

        {/* ========================= */}
        {/* LEFT: CHAT                 */}
        {/* ========================= */}

        <main className="chat-container">

          <div className="welcome-message">
            <h2>How are you feeling?</h2>

            <p>
              Describe your symptoms and I'll ask questions to better
              understand what's going on.
            </p>
          </div>

          <div className="messages">
            {messages.map((msg, index) => (
              <div
                key={index}
                className={`message ${
                  msg.role === "user"
                    ? "user-message"
                    : "ai-message"
                }`}
              >
                <strong>
                  {msg.role === "user"
                    ? "You"
                    : "Doctor AI"}
                </strong>

                <p>{msg.text}</p>
              </div>
            ))}
          </div>

        </main>


        {/* ========================= */}
        {/* RIGHT: ASSESSMENT          */}
        {/* ========================= */}

        <aside className="assessment-sidebar">

          <h2>Assessment</h2>

          {isLoading && (
            <p className="assessment-loading">
              Analyzing your latest answer...
            </p>
          )}

          {!assessment ? (

            <p className="assessment-placeholder">
              As you answer questions, your assessment will appear here.
            </p>

          ) : (

            <>

              {/* Summary */}

              {assessment.summary && (
                <section className="assessment-section">

                  <h3>Summary</h3>

                  <p>
                    {assessment.summary}
                  </p>

                </section>
              )}


              {/* Possible explanations */}

              {assessment.possibilities?.length > 0 && (
                <section className="assessment-section">

                  <h3>Possible explanations</h3>

                  {assessment.possibilities.map(
                    (possibility, index) => (

                      <div
                        key={index}
                        className={`possibility ${possibility.status}`}
                      >

                        <div className="possibility-header">

                          <strong>
                            {possibility.name}
                          </strong>

                          <span>
                            {possibility.status === "more_consistent"
                              ? "More consistent"
                              : possibility.status === "possible"
                              ? "Possible"
                              : "Less consistent"}
                          </span>

                        </div>

                        <p>
                          {possibility.reason}
                        </p>

                      </div>

                    )
                  )}

                </section>
              )}


              {/* Urgency */}

              {assessment.urgency && (
                <section className="assessment-section">

                  <h3>Urgency</h3>

                  <div
                    className={`urgency ${assessment.urgency.level}`}
                  >

                    <strong>
                      {assessment.urgency.level === "routine"
                        ? "Routine"
                        : assessment.urgency.level === "contact_clinician"
                        ? "Contact a healthcare professional"
                        : "Urgent"}
                    </strong>

                    <p>
                      {assessment.urgency.reason}
                    </p>

                  </div>

                </section>
              )}

            </>

          )}

        </aside>

      </div>


      {/* ========================= */}
      {/* INPUT AREA                 */}
      {/* ========================= */}

      {currentQuestion ? (

        <div className="question-area">
          {renderInput()}
        </div>

      ) : assessment?.assessment_complete ? (

        <div className="completed-message">
          <p>
            Assessment complete. You can start a new conversation
            when you're ready.
          </p>
        </div>

      ) : (

        <form
          className="input-area"
          onSubmit={handleSubmit}
        >

          <input
            type="text"
            placeholder="Describe your symptoms..."
            value={message}
            disabled={isLoading}
            onChange={(event) =>
              setMessage(event.target.value)
            }
          />

          <button type="submit" disabled={isLoading}>
            {isLoading ? "Thinking..." : "Send"}
          </button>

        </form>

      )}

    </div>
  );
}

export default App;